export const ACTION_TYPE = {
	SET_THEME: 'SET_THEME',
	LOGOUT: 'LOGOUT',
	SET_USER: 'SET_USER',
	SEND_FORM_REQUEST: 'SEND_FORM_REQUEST',
	SEND_FORM_SUCCESS: 'SEND_FORM_SUCCESS',
	SEND_FORM_FAILURE: 'SEND_FORM_FAILURE',
	RESET_FORM_STATE: 'RESET_FORM_STATE',
	SET_POST_DATA: 'SET_POST_DATA',
	RESET_POST_DATA: 'RESET_POST_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',

	ADD_COMMENT: 'ADD_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
};
