export const ACTION_TYPE = {
	SET_THEME: 'SET_THEME',
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_POST_DATA: 'SET_POST_DATA',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	RESET_POST_DATA: 'RESET_POST_DATA',
};
